### ISSUE TITLE
현재 develop 브런치에서 머지 해올때 주의사항

### ISSUE THREAD

**Issue by siyoon210** [JangHyeonJun2/jcjboard#13]
DB설정 충돌을 막기위해서 DBConfiguration파일이 추가되고, 각 Dao 파일의 필드값과 생성자 값을 변경하였습니다.

DBConfiguration 이라는 파일 제일 상단에 있는 필드에만, 본인의 DB설정을 넣어주시면 됩니다.
(그리고 앞으로 푸쉬하지 않도록 이그노어 해주세요)

각 Dao파일들의 생성자와 필드부분이 충돌 날 수있으니, 이것만 처음에 조정해주세요.

JSON파일 경로 찾는게 생각보다 어려워 JSON으로 연동은 포기했습니다.

**Comment by JangHyeonJun2** [comment]
넵 👍
