### ISSUE TITLE
댓글 작성하기 폼에 들어가야할 파라미터 입니다.

### ISSUE THREAD

**Issue by siyoon210** [JangHyeonJun2/jcjboard#17]
form method="post" action="/board/comment/write"
    이름 : input type="text" name="nickname"<br>
    비밀번호 : input type="password" name="password" <br>
    내용 : textarea name="content"></textarea<br>
    **현재 글의 ID를  "boardid"로 넘겨주어야함**
    button type="submit"댓글쓰기/button
/form

**Comment by JangHyeonJun2** [comment]
형 근데 현재 글의 ID를 boardid로 넘겨준다는게 자기 자신이 댓글을 단다는건가요?

**Comment by siyoon210** [comment]
아니 외래키로 사용할 글id가 있어야하자나 그걸위한 아이디
