### ISSUE TITLE
클래스명 파일명을 일관되게 정리해야 할것 같습니다

### ISSUE THREAD

**Issue by siyoon210** [JangHyeonJun2/jcjboard#30]
1) BoardDao에 경우는 현재 read서블릿 전용이므로 다른 Dao클래스명과 동일하게 BoardDaoRead 이런식으로 바꿔주세요
(담당하시는 현준님이)

2)jsp파일명도 일관성이 없으니 detail은 read로 바꿔주세요 (담당 현준)

3)boardwrite.jsp도 write로 변경하겠습니다
(제가 직접)

☆월요일에 강사님에게 코드리뷰도 해드려야하니 직관성을 위해서 바꿔주시고 앞으로 만들 클래스 파일명도 통일해주세요 화이띵

**Comment by JangHyeonJun2** [comment]
넵 알겠습니다 👍
