### ISSUE TITLE
DB Table 구조 변경.

### ISSUE THREAD

**Issue by jadie0319** [JangHyeonJun2/jcjboard#33]
alter table board modify regdate timestamp DEFAULT CURRENT_TIMESTAMP;
alter table comment modify regdate timestamp DEFAULT CURRENT_TIMESTAMP;

**Comment by jadie0319** [comment]
그리고 VO 파일들.(board, comment) 의 regdate 를 String 으로 변경해줘야함.

**Comment by jadie0319** [comment]
그리고 db2 파일에  서버타임존을 UTC를 아래로 바꿔줘야함.
 dbUrl = jdbc:mysql://localhost:3306/jcjboard?serverTimezone=Asia/Seoul&useSSL=false

**Comment by jadie0319** [comment]
풀 리퀘스트에 써놨는데. 왜 안보이는지....

**Comment by siyoon210** [comment]
띠용.. 전 그냥 서버타임존 안바꿧는데 잘 되네요 ㅋㅋ 일단 이 이슈는 닫겠습니다.
