### ISSUE TITLE
댓글이 달린 글을 삭제시 SQL에러가 발생함

### ISSUE THREAD

**Issue by siyoon210** [JangHyeonJun2/jcjboard#52]
외래키가 참조되어있어서 발생하는 에러로 보임

**Comment by jadie0319** [comment]
해결방법~! 

alter table comment drop foreign key comment_ibfk_1;
alter table comment add constraint comment_ibfk_1 foreign key (boardid) references board (boardid) on delete cascade on update  cascade;
